/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarymanagementsystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oluwatobi
 */
public class BookAndGenreChangePanel extends javax.swing.JFrame {
    
    private SystemManager Manage = new SystemManager();
    private String role;

    /**
     * Creates new form BookChangePanel
     */
    public BookAndGenreChangePanel(String role) {
        this.role = role;
        initComponents();
        updateBookTable();
        updateGenreComboBox(jComboBoxGenre);
    }

    /**
     * This method is called from within the constructor to initialize the form.WARNING: Do NOT modify this code.
     * The content of this method is always
 regenerated by the Form Editor.
     * @param combox
     */
    
    public final void updateGenreComboBox(JComboBox<String> combox){
        ResultSet rst  = Manage.createTableGenre();
        try {
            while(rst.next()){
                String temp = rst.getString(1) + " "+ rst.getString(2);
                combox.addItem(temp);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Table Code did not work in UpdateList");
        }
    }
    
    public final void updateBookTable(){
        ResultSet rst  = Manage.createTableBook();
        DefaultTableModel model = (DefaultTableModel) jTableBook.getModel();
        model.setRowCount(0);
        try {
            while(rst.next()){
                String temp = Manage.getGenreNamefromForeignKeyBook(rst.getString(1));
                if(temp == null)
                    JOptionPane.showMessageDialog(null, "Genre code did not Work");
                else{
                    model.addRow(new String[] {rst.getString(1), rst.getString(2), 
                    rst.getString(3), rst.getString(4), rst.getString(5), 
                    rst.getString(6), rst.getString(7), temp});
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Table Code did not work in UpdateList");
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxGenre = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBook = new javax.swing.JTable();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        jBDeselect = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();
        jBAddTo = new javax.swing.JButton();
        jBDeleteFrom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxGenre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Book  and Genre Change Panel");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        jTableBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Author", "Publisher", "Publication Date", "Date Created", "Dewey Decimal Number", "Genre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableBook);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Genre");

        jBDeselect.setText("Deselect");
        jBDeselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeselectActionPerformed(evt);
            }
        });

        jBCancel.setText("Cancel");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });

        jBAddTo.setText("Add to");
        jBAddTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddToActionPerformed(evt);
            }
        });

        jBDeleteFrom.setText("Delete from");
        jBDeleteFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDeleteFromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jBDeleteFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jBAddTo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jBCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBDeselect, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDeselect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAddTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBDeleteFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jBDeselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeselectActionPerformed
        // TODO add your handling code here:
        jTableBook.clearSelection();
    }//GEN-LAST:event_jBDeselectActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        // TODO add your handling code here:
        Manage.runFramePanel("Genre", role);
        dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    private void jBAddToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddToActionPerformed
        // TODO add your handling code here:
        String GenreID=(String) jComboBoxGenre.getSelectedItem();
        GenreID = GenreID.substring(0,1);
        String BookID;
        if (jTableBook.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "You have not slected a book" );
        }
        else{
            DefaultTableModel model = (DefaultTableModel) jTableBook.getModel();
            BookID = model.getValueAt(jTableBook.getSelectedRow(), 0).toString();
            String dialog = Manage.newGenreHasBook(GenreID, BookID);
            if(dialog == null)
                updateBookTable();
            else
                JOptionPane.showMessageDialog(null, dialog);              
        }
    }//GEN-LAST:event_jBAddToActionPerformed

    private void jBDeleteFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDeleteFromActionPerformed
        // TODO add your handling code here:
        String GenreID=(String) jComboBoxGenre.getSelectedItem();
        GenreID = GenreID.substring(0,1); 
        String BookID;
        if (jTableBook.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "You have not slected a book" );
        }
        else{
            DefaultTableModel model = (DefaultTableModel) jTableBook.getModel();
            BookID = model.getValueAt(jTableBook.getSelectedRow(), 0).toString();
            String dialog = Manage.deleteGenreHasBook(GenreID, BookID);
            if(dialog == null)
                updateBookTable();
            else
                JOptionPane.showMessageDialog(null, dialog);              
        }
    }//GEN-LAST:event_jBDeleteFromActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddTo;
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBDeleteFrom;
    private javax.swing.JButton jBDeselect;
    private javax.swing.JComboBox<String> jComboBoxGenre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBook;
    // End of variables declaration//GEN-END:variables
}
